services:
  caddy:
    container_name: caddy
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web-proxy-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  web-proxy-net:
    external: true
